import type { Business, Category, Offer, OfferWithBusiness, RegionSlug } from "./types";

export interface Region {
  id: number;
  name: string;
  slug: RegionSlug;
}

export interface StoreData {
  seedVersion: number;
  regions: Region[];
  businesses: Business[];
  offers: Offer[];
  nextBusinessId: number;
  nextOfferId: number;
}

/** Bump when replacing curated seed listings so existing stores refresh. */
export const CURRENT_SEED_VERSION = 2;

export function createSeedStore(): StoreData {
  const regions: Region[] = [
    { id: 1, name: "Metro Atlanta", slug: "metro-atlanta" },
    { id: 2, name: "North Georgia", slug: "north-georgia" },
    { id: 3, name: "Middle Georgia", slug: "middle-georgia" },
    { id: 4, name: "Coastal / Southeast", slug: "coastal" },
    { id: 5, name: "Southwest Georgia", slug: "southwest" },
    { id: 6, name: "Statewide", slug: "statewide" },
  ];

  const now = new Date().toISOString();
  const verified = "2026-09-04";

  const businesses: Business[] = [
    {
      id: 1,
      name: "Savannah Children's Museum",
      category: "museum",
      region_id: 4,
      address_line1: "655 Louisville Road",
      address_line2: null,
      city: "Savannah",
      state: "GA",
      zip: "31401",
      lat: 32.0753362,
      lng: -81.1025095,
      phone: "(912) 651-4292",
      website: "https://www.chsgeorgia.org/scm",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      name: "Atlanta Braves / Truist Park",
      category: "attraction",
      region_id: 1,
      address_line1: "755 Battery Ave SE",
      address_line2: null,
      city: "Atlanta",
      state: "GA",
      zip: "30339",
      lat: 33.890738,
      lng: -84.4676163,
      phone: null,
      website: "https://www.mlb.com/braves/tickets/specials",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      name: "Wild Animal Safari (Pine Mountain)",
      category: "zoo",
      region_id: 5,
      address_line1: "1300 Oak Grove Road",
      address_line2: null,
      city: "Pine Mountain",
      state: "GA",
      zip: "31822",
      lat: 32.899445,
      lng: -84.9237326,
      phone: "(706) 663-8744",
      website: "https://www.animalsafari.com",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 4,
      name: "Chick-fil-A Snellville (Scenic Hwy)",
      category: "restaurant",
      region_id: 1,
      address_line1: "1559 Scenic Highway",
      address_line2: null,
      city: "Snellville",
      state: "GA",
      zip: "30078",
      lat: 33.8876621,
      lng: -84.010031,
      phone: null,
      website: "https://www.chick-fil-a.com",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 5,
      name: "Rock Salt Milk Bar (Newnan)",
      category: "restaurant",
      region_id: 1,
      address_line1: "8 E Washington St",
      address_line2: null,
      city: "Newnan",
      state: "GA",
      zip: "30263",
      lat: 33.375309,
      lng: -84.7988599,
      phone: "(770) 683-3578",
      website: "https://rocksaltmilkbar.com/",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 6,
      name: "Good Kitchen + Market (Marietta)",
      category: "restaurant",
      region_id: 1,
      address_line1: "116 Margaret Ave NE",
      address_line2: null,
      city: "Marietta",
      state: "GA",
      zip: "30060",
      lat: 33.9661043,
      lng: -84.5487862,
      phone: null,
      website: "https://goodkitchenandmarket.com/",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 7,
      name: "Southern Baked Pie Company (Alpharetta)",
      category: "restaurant",
      region_id: 1,
      address_line1: "2685 Old Milton Pkwy",
      address_line2: "Suite 130",
      city: "Alpharetta",
      state: "GA",
      zip: "30009",
      lat: 34.0705,
      lng: -84.2733,
      phone: null,
      website: "https://www.southernbakedpie.com/pages/locations",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 8,
      name: "Georgia Aquarium",
      category: "aquarium",
      region_id: 1,
      address_line1: "225 Baker St NW",
      address_line2: null,
      city: "Atlanta",
      state: "GA",
      zip: "30313",
      lat: 33.7634,
      lng: -84.3951,
      phone: "(404) 581-4000",
      website: "https://www.georgiaaquarium.org/booking/our-community-access-program/",
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 9,
      name: "Zoo Atlanta",
      category: "zoo",
      region_id: 1,
      address_line1: "800 Cherokee Ave SE",
      address_line2: null,
      city: "Atlanta",
      state: "GA",
      zip: "30315",
      lat: 33.7341,
      lng: -84.372,
      phone: "(404) 624-5600",
      website: "https://zooatlanta.org/",
      active: 1,
      created_at: now,
      updated_at: now,
    },
  ];

  const offers: Offer[] = [
    {
      id: 1,
      business_id: 1,
      title: "50% off admission for foster families",
      description:
        "Savannah Children's Museum participates in Georgia Kids Belong’s Foster Friendly program. Foster families receive 50% off admission. Confirm current details with the museum or in the Foster Friendly App.",
      is_free: 0,
      discount_percent: 50,
      discount_details: "50% off general admission",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Licensed foster / kinship families in Georgia.",
      proof_required: "Foster parent ID or Foster Friendly card",
      source_url:
        "http://www.southernmamas.com/2023/50-discount-for-foster-families-savannah-childrens-museum/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      business_id: 2,
      title: "25% off Sunday home game tickets",
      description:
        "Atlanta Braves Foster Friendly offer: 25% off up to 12 tickets for any Sunday home game in non-premium seating (excluding Coca-Cola Corner and Standing Room Only). Sundays also include kids giveaways (first 3,000 kids 14 & under) and Kids Run the Bases after the game. Redeem via Foster Friendly App instructions.",
      is_free: 0,
      discount_percent: 25,
      discount_details: "25% off up to 12 Sunday home tickets (non-premium)",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster and kinship families (via Foster Friendly App).",
      proof_required: "Follow Braves offer steps in the Foster Friendly App",
      source_url: "https://www.mlb.com/braves/tickets/specials",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      business_id: 3,
      title: "Reduced admission for foster families",
      description:
        "Named by Georgia Kids Belong as a Foster Friendly attraction offering significantly reduced admission for foster families. Exact current rate can change — confirm at the gate or in the Foster Friendly App before visiting.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Significantly reduced admission (confirm current rate)",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster / kinship families via Foster Friendly program.",
      proof_required: "Foster parent ID or Foster Friendly card",
      source_url: "https://voyageatl.com/interview/meet-rebecca-radicchi-of-acworth/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 4,
      business_id: 4,
      title: "Foster Friendly Chick-fil-A partner",
      description:
        "Chick-fil-A Snellville (Scenic Hwy) was publicly welcomed by Georgia Kids Belong as a Foster Friendly partner. Ask in-store or check the Foster Friendly App for the current food/discount offer.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Foster Friendly CFA — confirm current offer in app",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster / kinship families.",
      proof_required: "Foster Friendly card or foster ID (confirm with restaurant)",
      source_url:
        "https://www.linkedin.com/posts/georgia-kids-belong_the-foster-friendly-app-continues-to-grow-activity-7448124297493172224--5c8",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 5,
      business_id: 5,
      title: "Foster Friendly ice cream partner",
      description:
        "Rock Salt Milk Bar was named by Georgia Kids Belong among Foster Friendly ice cream shops helping make cones affordable for foster families. Confirm the current discount at the Newnan shop or in the Foster Friendly App. Other Rock Salt locations may also participate — ask locally.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Foster Friendly ice cream offer — confirm in store/app",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster / kinship families.",
      proof_required: "Foster Friendly card or foster ID",
      source_url: "https://voyageatl.com/interview/meet-rebecca-radicchi-of-acworth/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 6,
      business_id: 6,
      title: "Foster Friendly restaurant partner",
      description:
        "Good Kitchen was named by Georgia Kids Belong among Atlanta-area Foster Friendly food partners helping feed foster families. Confirm the current offer at Marietta (and ask about Smyrna) or in the Foster Friendly App.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Foster Friendly dining offer — confirm current details",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster / kinship families.",
      proof_required: "Foster Friendly card or foster ID",
      source_url: "https://voyageatl.com/interview/meet-rebecca-radicchi-of-acworth/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 7,
      business_id: 7,
      title: "Foster Friendly bakery partner",
      description:
        "Southern Baked Pie Co was named by Georgia Kids Belong as a Foster Friendly Atlanta food partner. Confirm the current discount at Alpharetta or other pie shops (Buckhead, Vinings, Gainesville) via the Foster Friendly App.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Foster Friendly pie shop offer — confirm current details",
      starts_at: null,
      ends_at: null,
      eligibility_notes: "Foster / kinship families.",
      proof_required: "Foster Friendly card or foster ID",
      source_url: "https://voyageatl.com/interview/meet-rebecca-radicchi-of-acworth/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 8,
      business_id: 8,
      title: "Community Access Program (SNAP / eWIC)",
      description:
        "Not foster-ID specific: Georgia Aquarium’s Community Access Program offers deeply discounted admission for Georgia residents with an active Georgia SNAP or eWIC card. Vouchers must be purchased online in advance (limited daily supply). Many foster households may qualify via SNAP/WIC — verify eligibility on the Aquarium site.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Discounted CAP tickets for SNAP/eWIC (online vouchers)",
      starts_at: null,
      ends_at: null,
      eligibility_notes:
        "Georgia SNAP or eWIC cardholders only (not a foster-ID program).",
      proof_required: "Georgia SNAP/eWIC card + photo ID; buy voucher online",
      source_url:
        "https://www.georgiaaquarium.org/booking/our-community-access-program/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: 9,
      business_id: 9,
      title: "SNAP / WIC discounted admission & membership",
      description:
        "Not foster-ID specific: Zoo Atlanta offers discounted daytime admission and a reduced Family Membership for Georgia SNAP and WIC participants (redeemed in person with card + photo ID). Useful for foster families who also receive SNAP/WIC — confirm current rates on Zoo Atlanta’s site.",
      is_free: 0,
      discount_percent: null,
      discount_details: "Discounted tickets/membership for SNAP/WIC (in person)",
      starts_at: null,
      ends_at: null,
      eligibility_notes:
        "Georgia SNAP or WIC participants only (not a foster-ID program).",
      proof_required: "Georgia SNAP/EBT or WIC card + photo ID at admissions",
      source_url:
        "https://zooatlanta.org/press-release/zoo-atlanta-launches-a-new-access-program-for-snap-cardholders/",
      verified_at: verified,
      active: 1,
      created_at: now,
      updated_at: now,
    },
  ];

  return {
    seedVersion: CURRENT_SEED_VERSION,
    regions,
    businesses,
    offers,
    nextBusinessId: 10,
    nextOfferId: 10,
  };
}

export function joinOffer(
  offer: Offer,
  business: Business,
  region: Region,
): OfferWithBusiness {
  return {
    ...offer,
    business_name: business.name,
    category: business.category as Category,
    region_id: business.region_id,
    region_name: region.name,
    region_slug: region.slug,
    address_line1: business.address_line1,
    address_line2: business.address_line2,
    city: business.city,
    state: business.state,
    zip: business.zip,
    lat: business.lat,
    lng: business.lng,
    phone: business.phone,
    website: business.website,
    business_active: business.active,
  };
}

export function isOfferCurrent(offer: Offer, today = new Date()) {
  if (!offer.ends_at) return true;
  const end = new Date(
    offer.ends_at.length === 10 ? `${offer.ends_at}T23:59:59` : offer.ends_at,
  );
  return end >= today;
}
